name: "Build ESP32-S3-BOX Factory Demo"

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-factory-demo:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build factory_demo
        shell: bash
        run: |
          # Source ESP-IDF environment
          . $IDF_PATH/export.sh

          # Install required Python dependencies
          pip install --upgrade idf-component-manager
          pip install "idf_build_apps<2.0"

          # Go to the example folder
          cd $GITHUB_WORKSPACE/examples/factory_demo

          # Merge SDK config defaults for box-3
          comm -23 <(grep -v '^#' sdkconfig.ci.box-3 | sort) \
                    <(grep -v '^#' sdkconfig.defaults | sort) | \
                    sed 's/.*/\n&/' >> sdkconfig.defaults

          # Build the project
          idf.py build

          # Create a single merged BIN for flashing
          idf.py fullflash -o $GITHUB_WORKSPACE/factory_demo_box3.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: factory-demo-box3
          path: $GITHUB_WORKSPACE/factory_demo_box3.bin
          overwrite: true
