name: Build ESP32-S3-BOX Factory Demo

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.1

    steps:
      - name: Checkout esp-box
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Factory Demo (ESP32-S3-BOX)
        shell: bash
        run: |
          # Load ESP-IDF environment
          . $IDF_PATH/export.sh

          # Go to factory demo
          cd examples/factory_demo

          # Set correct chip
          idf.py set-target esp32s3

          # IMPORTANT:
          # Copy correct CI config BEFORE first build
          cp sdkconfig.ci.box sdkconfig

          # Clean + build
          idf.py fullclean build

          # Merge into single flashable binary
          cd build

          APP_BIN=$(ls *.bin | grep -v bootloader | grep -v partition)

          esptool.py --chip esp32s3 merge_bin \
            -o factory_demo_box.bin \
            --flash_mode dio \
            --flash_size 16MB \
            0x0 bootloader/bootloader.bin \
            0x8000 partition_table/partition-table.bin \
            0x20000 $APP_BIN

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-S3-BOX-factory-demo
          path: examples/factory_demo/build/factory_demo_box.bin
